/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafka.generator;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class ProducerTest {
    @Test public void appHasAGreeting() {
        Producer classUnderTest = new Producer();
        assertNotNull("should start", classUnderTest);
    }
}
